### PR TITLE
Fixes #468 (extra trial data) - update to prevent rerender

### LINKED ISSUE #468: Incorrect Trial/extra trial data instance creation
When a user navigates directly to a new benchmark (without trial data) via the url benchmarks/[id]/instructions url and then clicks "collect data", trial 2 is sometimes displayed instead of trial 1.

Further insight: I monitored the table "trial_data", and after clicking collect data (at the above url), two trial data instances are created.

See benchmark-instructions branch for some comments on behavior (https://github.com/sfbrigade/compass/commit/f289283b0c48620d809e655c012075866d412e50)

image
image

### PR DESCRIPTION
**Pull request by katconnors**
Behavior described in issue #468 is no longer occuring. 
Source of the problem was that useEffect was causing a rerender of the benchmark component in development.

### CODE REVIEW

File: src/pages/benchmarks/[benchmark_id]/index.tsx [hunk 1]
```diff
@@ -71,7 +71,7 @@ const BenchmarkPage = () => {
   const [currentTrialIdx, setCurrentTrialIdx] = useState(0);
   const currentTrial = task?.trials[currentTrialIdx] || null;
 
-  const [trialAdded, setTrialAdded] = useState(false);
+  const trialAddedRef = useRef(false);
```
Comment (canjalal) [inline src/pages/benchmarks/[benchmark_id]/index.tsx:74]: nitpick: can you type this as `useRef<boolean>(false)`?

**Review by canjalal — APPROVED** [review]

File: src/pages/benchmarks/[benchmark_id]/index.tsx (hunk 1 above)
Comment (katconnors) [reply src/pages/benchmarks/[benchmark_id]/index.tsx:74]:
```suggestion
  const trialAddedRef = useRef<boolean>(false);
```
